name: "âš™ï¸ CI feature branch"

on:
  push:
    branches:
      - feature**
      - '[0-9].[0-9].x'
      - 'v[0-9].[0-9].[0-9]'
      - 'v[0-9].[0-9].x'
      - docs**

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  ci-python:
    name: ðŸ ci-python
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ”„ Checkout
        uses: actions/checkout@v4

      - name: ðŸ Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: ðŸ“¦ Dependencies Setup
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt
      
      - name: ðŸ“ Linter Analysis with Pylint
        run:
          pylint --rcfile=.pylintrc app
      
      - name: ðŸ”Ž Static Type Analysis with Mypy
        run:
          mypy app

      - name: ðŸ§ª Unit Test with Pytest
        run:
          pytest -vv --color=yes --cov=./ --cov-report=xml

      - name: â˜‚ï¸ Test Coverage with Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  ci-terraform:
    name: ðŸ› ï¸ ci-terraform
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ”„ Checkout
        uses: actions/checkout@v4

      - name: â›ï¸ Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init
        working-directory: infra/aws/get-active-tickers

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/aws/get-active-tickers

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra/aws/get-active-tickers

  open-pr-to-main:
    name: ðŸ”“ open-pr-to-main
    runs-on: ubuntu-latest
    needs:
      - ci-python
      - ci-terraform

    steps:
      - name: ðŸ”„ Checkout
        uses: actions/checkout@v4

      - name: ðŸ”“ PR to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref }}
          destination_branch: "main"
          pr_title: "pr(main): ${{ github.ref }} -> main"
          pr_template: ".github/pull_request_template.md"
          pr_assignee: "ThiagoPanini"
          pr_label: "github-bot ðŸ¤–"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ”“ PR to main
        uses: peter-evans/create-pull-request@v7
        with:
          base: ${{ github.ref }}
          title: "pr(main): ${{ github.ref }} -> main"
          body-path: ".github/pull_request_template.md"
          labels: "github-bot ðŸ¤–"
          
